# Application port
server:
  port: 8080

# Default connection pool
spring:
  datasource:
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
  # PostgreSQL
    url: jdbc:postgresql://localhost:5432/dev
    username: postgres
    password: postgres

  # Default Schema
  flyway:
    schemas: users
    baseline-on-migrate: true
    clean-disabled: false
    repair: true
  jpa:
    properties:
      hibernate:
        default_schema: users
